output_dir: "./results"
model_name: './weights/model_unet'
in_channels: 1
out_channels: 2
datasets_length: 205
num_epochs: 150
batch_size: 8
lr: 0.0003
weight_decay: 0.0001
decay_interval: 50

